services:

  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

volumes:
  database_data:
